'''
Converting distance from km to meter, feet, inchs and centimeter
'''
DISTANCE_IN_KILOMETER = int(input("Enter the Distance in KM: "))
DISTANCE_IN_METER = DISTANCE_IN_KILOMETER*1000
DISTANCE_IN_INCH = DISTANCE_IN_METER*39.3701
DISTANCE_IN_FEET = DISTANCE_IN_INCH/12
DISTANCE_IN_CENTIMETER = DISTANCE_IN_INCH*2.54
print(f"DISTANCE_IN_KILOMETER :{DISTANCE_IN_KILOMETER}")
print(f"DISTANCE_IN_METER :{DISTANCE_IN_METER}")
print(f"DISTANCE_IN_Inch :{DISTANCE_IN_INCH}")
print(f"DISTANCE_IN_FEET :{DISTANCE_IN_FEET}")
print(f"DISTANCE_IN_CENTIMETER :{DISTANCE_IN_CENTIMETER}")
