'''
calculating gross salary
'''
BASE_SALARY = int(input("Enter the BASE SALARY: "))
RENT_ALLOWANCE = (BASE_SALARY*20)/100
DEARNESS_ALLOWANCE = (BASE_SALARY*60)/100
GROSS_SALARY = BASE_SALARY+RENT_ALLOWANCE+DEARNESS_ALLOWANCE
print(f"Base SALARY :{BASE_SALARY}")
print(f"DISTANCE ALLOWANCE :{DEARNESS_ALLOWANCE}")
print(f"RENT_ALLOWANCE :{RENT_ALLOWANCE}")
print(f"GOSS SALARY :{GROSS_SALARY}")
