'''
Reverse the inutted number
'''
INITIAL_NUMBER = int(input("Enter the number"))
REVERSE= 0
LAST_NUMBER1 = INITIAL_NUMBER%10
REVERSE = (REVERSE*10)+LAST_NUMBER1
INITIAL_NUMBER1= INITIAL_NUMBER//10

LAST_NUMBER2 = INITIAL_NUMBER1%10
REVERSE = (REVERSE*10)+LAST_NUMBER2
INITIAL_NUMBER2 = INITIAL_NUMBER1//10

LAST_NUMBER3 = INITIAL_NUMBER2%10
REVERSE = (REVERSE*10)+LAST_NUMBER3
INITIAL_NUMBER3 = INITIAL_NUMBER2//10

LAST_NUMBER4 = INITIAL_NUMBER3%10
REVERSE = (REVERSE*10)+LAST_NUMBER4
INITIAL_NUMBER4 = INITIAL_NUMBER3//10

LAST_NUMBER5 = INITIAL_NUMBER4%10
REVERSE = (REVERSE*10)+LAST_NUMBER5
print(REVERSE)
